### ISSUE TITLE
SchemaView should handle shared attributes with shared names appropriately

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml-runtime#210]
```yaml
classes:
  C:
    attributes:
      a:
         ...
  D:
    attributes:
      a:
          ...
```

when using methods such as induced_slot that are contextualized by class, the behavior is umabiguous

however, when using the general get_slots method, the behavior can be ambiguous for fetching attribute `a`. SchemaView should return a slot when attributes=True is passed.
