### ISSUE TITLE
Pure number tags don't parse correctly

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml-runtime#3]
```yaml
  sample_enum:
    description: Type of material sample
    permissible_values:
      0: Blood
```

Breaks the parser because we try to construct a permissible value with `(0="Blood")`
