### ISSUE TITLE
`YAMLDumper`: Add deduplication functionality (bug?)

### ISSUE THREAD

**Issue by joeflack4** [linkml/linkml-runtime#53]
## Description of issue experienced
Gaurav noticed duplicates when testing out the enumerations endpoint.
Example: https://terminology.ccdh.io/enumerations/CRDC-H.Treatment.treatment_effect?value_only=true
Original issue: https://github.com/cancerDHC/ccdh-terminology-service/issues/27 

## Possible solution
While I can dedupe in the terminology service, and am doing so, I am thinking that the best place to do this deduping is probably in the YAMLDumper (if not somewhere higher up in the abstraction chain). 

The class right now is pretty light:
```python
class YAMLDumper(Dumper):

    def dumps(self, element: YAMLRoot, **kwargs) -> str:
        """ Return element formatted as a YAML string """
        return yaml.dump(remove_empty_items(element, hide_protected_keys=True),
                                            Dumper=yaml.SafeDumper, sort_keys=False, **kwargs)
```

You can see the deduping I have in mind as pseudocode in the [terminology service GitHub issue](https://github.com/cancerDHC/ccdh-terminology-service/issues/27 ).

## Discussion
@cmungall I marked this as a "bug" and put it under the project "Generation of APIs..." since it has an effect on our APIs. I'm considering you the steward of LinkML, so I'm wondering if you agree with my approach. If so, this should not be difficult for me to do.

**Comment by cmungall** [comment]
I think the fix here is to throw an error at parse time if dupes are found?

This already happens if you have duplicate classes, slots, etc

**Comment by joeflack4** [comment]
Hmm, that makes sense. I wonder if it makes sense though that in some cases the user would want / there would be a reason to support having duplicates in some objects. The are probably a large classes that are `YAMLDumper`-able.

## Problem 1: Where to implement anti-duping logic
In the case of handling this at parse time, so to speak, this could get a little hairy given that this deduping or anti-duping check would have to be added for each class (e.g. `EnumDefinition`), or otherwise would have to be implemented at a more abstract level, such as `Element` or `YAMLRoot`.

Hairier still is that there's more than 1 way in which duplicates might arrive somewhere within a `YAMLDumper`-able object. In the particular case where I'm experiencing an issue, for example, it happens not at a "parse time" necessarily, or even object instantiation time. It happens when we are doing `EnumDefinition.permissible_values.append()`.

Here's the link to the original issue that I fixed: https://github.com/cancerDHC/ccdh-terminology-service/issues/27

Here's a code snippet from the terminology service showing where this issue occurred (last line):
```python
async def get_enumeration(name: str, value_only: bool = False) -> Response:
    system, entity, attribute = name.split('.')
    enum = EnumDefinition(name=name, description=f'Autogenerated Enumeration for {system} {entity} {attribute}')
    enum.permissible_values = []
    if value_only:
        values = mdr_graph.find_permissible_values_of(system, entity, attribute)
        for v in values:
            enum.permissible_values.append(PermissibleValue(text=v['pref_label'], description=v['description']))
```

So, the check here would have to happen at `.append()` on the `permissible_values` list attribute. 

I'm thinking about the best way to do this. I can think of 2 different locations / kinds of locations where we could add this anti-dupe logic:

a. Use getters and setters
b. Overload `Element.__setattr__(self, name, value)` ([example](https://stackoverflow.com/questions/19869799/catching-changes-to-a-mutable-attribute-in-python))

For better or worse, I'm generally a DRY / dynamic type programmer, so I prefer (b) i n this case. What do you think?

Caveats
- We would still need to add custom logic. Checking for dupes would be different depending on the data structure of the given attribute being manipulated.
- I'm not sure that change (b) would cover every instance of attribute mutation. I suppose when setting attributes during object construction, this method would still be used. But I imagine there are other ways to create/update object attributes that might not be covered by overloading `__setattr__`.

## Problem 2: What constitutes a duplicate?
The case of the duplicate in the [original issue](https://github.com/cancerDHC/ccdh-terminology-service/issues/27) looked like this:

```yml
name: CRDC-H.Treatment.treatment_effect
description: Autogenerated Enumeration for CRDC-H Treatment treatment_effect
permissible_values:
- text: 'Yes'
- text: Not Reported  # <---1
- text: Unknown  # <---2
- text: 'No'
- text: Unknown  # <---2
  description: Unknown
- text: Incomplete Necrosis (Viable Tumor Present)
- text: No Necrosis
- text: No Known Treatment Effect
- text: Complete Necrosis (No Viable Tumor)
- text: Not Reported  # <---1
  description: Not Reported
```

### Kinds of duplicates
A. Duplicate of equivalency
B. Duplicate by subset

The pairs of duplicates labeled (1) and (2) in the example above are not duplicates in the sense that they are (A) _wholly equivalent objects / values_. The duplicates herein are defined as duplicates in the sense that one object can be said to be a (B) _subset of another object_, e.g. `{"text": "Unknown"}` is a subset of `{"text": "Unknown", "description": "Unknown"}`

For reference, here's how I did duplication checking in this case

```python
def is_nonequivalent_subset(subset, superset):
    """Is subset actually a subset of superset, and not wholly equivalent?"""
    return is_subset(subset, superset) and subset != superset

def is_subset(subset, superset):
    """Is subset actually a subset of superset."""
    if isinstance(subset, dict):
        return all(key in superset and is_subset(val, superset[key]) for key, val in subset.items())
    if isinstance(subset, list) or isinstance(subset, set):
        return all(any(is_subset(subitem, superitem) for superitem in superset) for subitem in subset)
    return subset == superset

...

    val_objs: Dict[str, str] = enum_dict['permissible_values']
    for val_obj in val_objs:
        for i in range(len(enum_dict['permissible_values'])):
            original_val_obj = enum_dict['permissible_values'][i]
            subset_found = is_nonequivalent_subset(original_val_obj, val_obj)
            if subset_found:
                enum_dict['permissible_values'][i] = 'dupe'
    enum_dict['permissible_values'] = [
        x for x in enum_dict['permissible_values'] if x != 'dupe']
```

---

Does it make sense to close this issue and create a more general "anti-dupe" issue? (I can link back to this issue for context).

**Comment by cmungall** [comment]
So I think this may be simpler

metamodel:

```yaml
classes:
permissible_value:
    description: a permissible value, accompanied by intended text and an optional mapping to a concept URI
    mixins:
      - extensible
      - annotatable
      - common_metadata
    slot_usage:
      is_a:
        range: permissible_value
      mixins:
        range: permissible_value
    slots:
      - text
      - description
      - meaning
...
slots:  
  text:
    domain: permissible_value
    range: string
    identifier: true
```

linkml:text is declared is declared as an identifier - this is why it's valid to use it as a key when inlining permissible values under an enum. The key should always be unique. This is true for any model, including the metamodel. I'm surprised that errors aren't thrown when loading any inlined-as-dict structure with non-unique keys.
